import { Toaster } from "sonner";

import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Providers from "../lib/Providers/Providers";

export const metadata = {
  title: "Ecommerce",
  description: "Generated by Hasibul Hasan",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className="font-Montserrat">
          <AppRouterCacheProvider>
            <Toaster position="top-right" richColors />
            {children}
          </AppRouterCacheProvider>
        </body>
      </html>
     </Providers>
  );
}
