import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/shead/navbar/Navbar";
import Footer from "./Component/shead/footer/Footer";
import BgColor from "./Component/Container/BgColor";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar />
        <BgColor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
